### ISSUE TITLE
Course says it's Free as in Freedom, but uses a non-free license

### ISSUE THREAD

**Issue by emacsen** [Esperanto/kurso-zagreba-metodo#37]
The CC-BY-ND license used by (https://github.com/Esperanto/kurso-zagreba-metodo/blob/master/enhavo/netradukenda/tekstoj/PERMESILO.md) which is used in this course does is not a Free Culture license due to the ND terms (https://creativecommons.org/freeworks/), but the http://learn.esperanto.com/en/ website says that it's "Free as in Freedom". 

Since this is incorrect, please fix either the language or the license.

**Comment by georgjaehnig** [comment]
Hi,

so as you already corrected yourself, the (partial) license is CC-BY-ND (not NC). That means commercial usage is allowed, just changes are not.

And secondly, the ND part __only__ applies to the Esperanto reading texts, so only to the 12 files in [this directory](https://github.com/Esperanto/kurso-zagreba-metodo/tree/master/enhavo/netradukenda/tekstoj). The whole other content is under the CC-BY license, so it can be freely changed and edited.

Now, the reason for having a separate ND-license for the reading texts: The authors wanted to make sure that the idea of the course, i.e. that it covers the most frequent 500 words, is saved. Because this is what the course is about. The words were deliberately chosen on their usage, and using other words / texts could make the course not fulfilling its promise.

Still, I'm not insisting on "free as in freedom". I just wanted to point out that it's not only free to use (like many other course) but that the content is also freely distributable and usable in people's own projects. If you have a better line for this then suggest one.

**Comment by emacsen** [comment]
Having a typo in the original bug report is irrelevant to the issue.

Please remove the claim to being "Free as in Freedom" if the license is in fact not Free. It's quite a simple thing.

As for your claim that people can use it in their own projects, this is exactly contradictory to the terms in ND, since the content can't be modified to other uses, but this is a separate issue than the one I'm presenting, which is your claim that the work is distributed under terms which it is not. If you'd like to open another issue for this second issue, that's fine but separate.
